#!/usr/bin/env python3
"""
check_offsets.py — assert a hook map's declared ctx offsets against the real header.

This is the check that a per-build hook-map generator MUST have, and whose absence
was demonstrated in this very repo: an earlier revision of
hook-point-map.json omitted the `mode` field of `struct ls_ctx`, so any
tool that re-derived offsets by packing the field list computed `head` at byte 8
when it actually lives at byte 12. A shield reading `head` would have read
`mode`'s four bytes plus twelve bytes of `head`, and every artifact in the repo
still validated, because a hash of a wrong map is a wrong map.

The fix is mechanical: generate a C translation unit full of _Static_asserts from
the map's own field_offsets/ctx_size, compile it against the real header, and fail
the build on mismatch. Offsets are then verified, not asserted by a human.

Usage:  ./check_offsets.py [map.json]      (default: ./hook-point-map.json)
"""
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_MAP = os.path.join(HERE, "hook-point-map.json")

# Which header + struct backs each argument type in the prototype build. In
# product this comes from the map's own debug-info provenance, not a table.
TYPE_TO_HEADER = {
    "const struct ls_ctx *": ("example_hook_ctx.h", "struct ls_ctx"),
    "struct ls_ctx *":       ("example_hook_ctx.h", "struct ls_ctx"),
}


def gen_tu(hook, arg_name, arg):
    """Emit _Static_asserts for every declared offset, plus the struct size."""
    header, ctype = TYPE_TO_HEADER[arg["type"]]
    lines = [
        "/* generated by check_offsets.py — do not edit */",
        "#include <stddef.h>",
        '#include "%s"' % header,
    ]
    offsets = arg.get("field_offsets", {})
    for field, off in sorted(offsets.items(), key=lambda kv: kv[1]):
        lines.append(
            '_Static_assert(offsetof(%s, %s) == %d,\n'
            '    "%s.%s.%s: hook map says %d");'
            % (ctype, field, off, hook, arg_name, field, off))
    if "ctx_size" in arg:
        lines.append(
            '_Static_assert(sizeof(%s) == %d,\n'
            '    "%s.%s: hook map ctx_size says %d");'
            % (ctype, arg["ctx_size"], hook, arg_name, arg["ctx_size"]))

    # Every field in `fields` must also carry an offset — the omission that bit us
    # is exactly a field present in the struct but absent from the map, so also
    # assert the reverse direction is at least self-consistent.
    missing = set(arg.get("fields", {})) - set(offsets)
    return "\n".join(lines) + "\n", missing


def main(argv):
    path = argv[1] if len(argv) > 1 else DEFAULT_MAP
    doc = json.load(open(path))
    rel = os.path.relpath(path, HERE)

    cc = os.environ.get("CC", "cc")
    rc = 0
    checked = 0

    for hp in doc.get("hook_points", []):
        for arg_name, arg in sorted(hp.get("arg_btf", {}).items()):
            if arg["type"] not in TYPE_TO_HEADER:
                print("skip  %s %s.%s (no header mapping for %r)"
                      % (rel, hp["name"], arg_name, arg["type"]))
                continue
            if "field_offsets" not in arg:
                print("FAIL  %s %s.%s: no field_offsets — offsets cannot be "
                      "verified, and re-deriving them by packing is unsound"
                      % (rel, hp["name"], arg_name))
                rc = 1
                continue

            tu, missing = gen_tu(hp["name"], arg_name, arg)
            if missing:
                print("FAIL  %s %s.%s: fields with no declared offset: %s"
                      % (rel, hp["name"], arg_name, ", ".join(sorted(missing))))
                rc = 1

            with tempfile.NamedTemporaryFile("w", suffix=".c", dir=HERE,
                                             delete=False) as f:
                f.write(tu)
                tmp = f.name
            try:
                p = subprocess.run([cc, "-fsyntax-only", "-I", HERE, tmp],
                                   capture_output=True, text=True)
                if p.returncode != 0:
                    print("FAIL  %s %s.%s: offsets do not match the header"
                          % (rel, hp["name"], arg_name))
                    for line in p.stderr.splitlines():
                        if "static assertion" in line or "_Static_assert" in line:
                            print("        %s" % line.strip())
                    rc = 1
                else:
                    n = len(arg.get("field_offsets", {}))
                    print("ok    %s %s.%s (%d offsets + ctx_size verified "
                          "against the real header)"
                          % (rel, hp["name"], arg_name, n))
                    checked += 1
            finally:
                os.unlink(tmp)

    if checked == 0 and rc == 0:
        print("warn  nothing verified — no arg had a header mapping")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
