#!/usr/bin/env python3
"""Generate ls_sig_pubkey.h --- the public key compiled into TMM.

    gen_sig_pubkey.py <pubkey.pem|pubkey.der> -o ls_sig_pubkey.h
    gen_sig_pubkey.py --none            -o ls_sig_pubkey.h    # a build that verifies nothing

WHY GENERATED RATHER THAN CHECKED IN. The key that a build trusts is a property of that build,
and writing it by hand into a header is how a test key reaches production. This reads the actual
key file, extracts the 32 raw bytes from the SubjectPublicKeyInfo wrapper, and records the
fingerprint in a comment so the header itself says which key it carries.

--none EXISTS AND IS NOT A CONVENIENCE. A build with no key refuses every load, which is the
correct default for a tree nobody has configured. It must be a deliberate, visible choice rather
than what you get by forgetting to run this --- so the generated header says so loudly, and
ls_sig.c treats an all-zero key as absent rather than as a key.
"""
import argparse
import hashlib
import subprocess
import sys


def raw_from_pem(path):
    """The 32 raw Ed25519 bytes out of a PEM/DER public key.

    openssl rather than a Python crypto dependency: the signing side already needs openssl and
    the build box has it, so this adds nothing. The DER SubjectPublicKeyInfo for Ed25519 is 44
    bytes with the key in the last 32 --- checked rather than assumed, because silently taking
    the tail of a longer structure would embed the wrong bytes.
    """
    der = subprocess.run(["openssl", "pkey", "-pubin", "-in", path, "-pubout", "-outform", "DER"],
                         capture_output=True)
    if der.returncode != 0:
        der = subprocess.run(["openssl", "pkey", "-in", path, "-pubout", "-outform", "DER"],
                             capture_output=True)
    if der.returncode != 0:
        sys.exit("*** openssl could not read %r as a key:\n    %s"
                 % (path, der.stderr.decode(errors="replace").strip()[:300]))
    b = der.stdout
    if len(b) != 44:
        sys.exit("*** expected a 44-byte Ed25519 SubjectPublicKeyInfo, got %d bytes.\n"
                 "    That is probably not an Ed25519 key --- this refuses rather than taking\n"
                 "    the last 32 bytes of something else." % len(b))
    return b[-32:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("key", nargs="?")
    ap.add_argument("--none", action="store_true",
                    help="emit a header with NO key, so the build refuses every load")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    if a.none:
        raw, fp, origin = bytes(32), "none", "no key --- this build verifies nothing"
    else:
        if not a.key:
            sys.exit("*** give a key file, or --none to build a tree that refuses every load")
        raw = raw_from_pem(a.key)
        fp = hashlib.sha256(raw).hexdigest()
        origin = a.key

    L = []
    L.append("/* GENERATED by substrate/gen_sig_pubkey.py --- do not edit.")
    L.append(" *")
    L.append(" * The Ed25519 public key this build will accept signatures from.")
    L.append(" *   origin      : %s" % origin)
    L.append(" *   sha256(key) : %s" % fp)
    L.append(" *")
    if a.none:
        L.append(" * THIS BUILD HAS NO KEY, so ls_sig_verify refuses every load with LS_SIG_NO_PUBKEY.")
        L.append(" * That is the correct default for an unconfigured tree: a build that cannot verify")
        L.append(" * must not accept. An all-zero key is treated as ABSENT rather than as a key,")
        L.append(" * because zero is a valid Ed25519 point and would otherwise verify nothing while")
        L.append(" * looking configured.")
    else:
        L.append(" * Regenerate whenever the signing key changes. The fingerprint above is what an")
        L.append(" * operator compares against the signing service's key --- if they differ, this")
        L.append(" * build trusts something else.")
    L.append(" */")
    L.append("#ifndef LS_SIG_PUBKEY_H")
    L.append("#define LS_SIG_PUBKEY_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append("#define LS_SIG_PUBKEY_LEN 32u")
    L.append("")
    L.append("/* Offsets into struct shield_binding, asserted against the ABI in check_sig.c so")
    L.append(" * this header cannot drift from shield_abi.h without a build failure. */")
    L.append("#define LS_SIG_BINDING_LEN      112u")
    L.append("#define LS_SIG_BINDING_HASH_OFF   0u")
    L.append("")
    L.append("static const uint8_t ls_sig_pubkey[LS_SIG_PUBKEY_LEN] = {")
    for i in range(0, 32, 8):
        L.append("    " + " ".join("0x%02x," % b for b in raw[i:i + 8]))
    L.append("};")
    L.append("")
    L.append("#endif /* LS_SIG_PUBKEY_H */")
    with open(a.out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("  %s: %s (sha256 %s)" % (a.out, "NO KEY" if a.none else "key embedded", fp[:16]))


if __name__ == "__main__":
    main()
