/* GENERATED by substrate/gen_sig_pubkey.py --- do not edit.
 *
 * The Ed25519 public key this build will accept signatures from.
 *   origin      : /home/claude/.ls-signing/shield_pk.pem
 *   sha256(key) : b4695cde1d86c243c87400f88f01e993a4a698a1baeb0b54809d7b0717e87793
 *
 * Regenerate whenever the signing key changes. The fingerprint above is what an
 * operator compares against the signing service's key --- if they differ, this
 * build trusts something else.
 */
#ifndef LS_SIG_PUBKEY_H
#define LS_SIG_PUBKEY_H

#include <stdint.h>

#define LS_SIG_PUBKEY_LEN 32u

/* Offsets into struct shield_binding, asserted against the ABI in check_sig.c so
 * this header cannot drift from shield_abi.h without a build failure. */
#define LS_SIG_BINDING_LEN      112u
#define LS_SIG_BINDING_HASH_OFF   0u

static const uint8_t ls_sig_pubkey[LS_SIG_PUBKEY_LEN] = {
    0xd0, 0x5a, 0x15, 0x9b, 0x1e, 0x5b, 0xf6, 0x2f,
    0x17, 0x11, 0x2d, 0x00, 0x19, 0x48, 0x43, 0xba,
    0xc3, 0xd6, 0x8e, 0xe3, 0xdc, 0x64, 0xd4, 0x05,
    0x27, 0x6e, 0xcb, 0x0d, 0xbf, 0x9a, 0x8c, 0x1d,
};

#endif /* LS_SIG_PUBKEY_H */
