/* ls_sig.c --- the Ed25519 verification itself. See ls_sig.h for what is signed and why. */
#include "ls_sig.h"
/* ANGLE BRACKETS, and the difference is load-bearing. ls_sig_pubkey.h is a BUILD ARTIFACT ---
 * generated by gen_sig_pubkey.py from whichever key this build trusts --- not a source file
 * sitting next to this one. A quoted include searches this file's own directory first, ahead of
 * every -I, so `#include "ls_sig_pubkey.h"` silently pinned the key to whatever copy happened to
 * be committed in substrate/, and no -I order could override it.
 *
 * That is not a style point. It made the signature test verify a freshly signed program against
 * a stale committed key and report a failure of its own construction --- the most confusing way
 * for a security check to fail, and it would have done the same to any build that generated its
 * key somewhere other than this directory. */
#include <ls_sig_pubkey.h>

#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/sha.h>

#include <stdio.h>
#include <string.h>

const char *
ls_sig_strerror(enum ls_sig_result r)
{
    switch (r) {
    case LS_SIG_OK:             return "ok";
    case LS_SIG_NO_PUBKEY:      return "no public key is baked into this build";
    case LS_SIG_BAD_ARGS:       return "malformed request (length or pointer)";
    case LS_SIG_EVP_FAILED:     return "the crypto library could not attempt verification";
    case LS_SIG_BAD_SIGNATURE:  return "signature is INVALID for these bytes and this key";
    case LS_SIG_EVP_ERROR:      return "the crypto library FAILED (not a verdict about the "
                                       "program --- see the ls_sig: line in the log)";
    case LS_SIG_BODY_MISMATCH:  return "signature is valid but the program body does not match "
                                       "the hash it commits to";
    }
    return "unknown";
}

int
ls_sig_have_pubkey(void)
{
    /* An all-zero key is the "unset" state that a generated header with no key produces. Treat
     * it as absent rather than as a key, because a zero key is a valid Ed25519 point and would
     * otherwise silently verify nothing while looking configured. */
    unsigned i;

    if (LS_SIG_PUBKEY_LEN != 32u)
        return 0;
    for (i = 0; i < LS_SIG_PUBKEY_LEN; i++)
        if (ls_sig_pubkey[i] != 0)
            return 1;
    return 0;
}

enum ls_sig_result
ls_sig_verify(const void *binding, size_t binding_len,
              const uint8_t *sig, size_t sig_len,
              const void *prog, size_t prog_len)
{
    EVP_PKEY *pk = NULL;
    EVP_MD_CTX *ctx = NULL;
    enum ls_sig_result rc = LS_SIG_EVP_FAILED;
    unsigned char want[32];
    const unsigned char *claimed;

    /* ARGUMENTS FIRST, because a caller controls every one of them. A short binding is refused
     * rather than padded: padding would make two different requests verify against one
     * signature. */
    if (binding == NULL || sig == NULL || prog == NULL)
        return LS_SIG_BAD_ARGS;
    if (binding_len != LS_SIG_BINDING_LEN || sig_len != 64u || prog_len == 0)
        return LS_SIG_BAD_ARGS;
    if (!ls_sig_have_pubkey())
        return LS_SIG_NO_PUBKEY;

    /* FINGERPRINT WHAT IS ABOUT TO BE VERIFIED. Three separate checks outside TMM said the
     * binding, the signature and the key were all correct while the live path refused --- and
     * there was no way to tell which of them TMM was actually looking at. Eight bytes each is
     * enough to identify them and short enough to log on every load. */
    {
        unsigned char bh[32];
        if (SHA256((const unsigned char *)binding, binding_len, bh) != NULL)
            fprintf(stderr, "ls_sig: verifying binding %02x%02x%02x%02x sig %02x%02x%02x%02x "
                            "key %02x%02x%02x%02x prog %u bytes\n",
                    bh[0], bh[1], bh[2], bh[3], sig[0], sig[1], sig[2], sig[3],
                    ls_sig_pubkey[0], ls_sig_pubkey[1], ls_sig_pubkey[2], ls_sig_pubkey[3],
                    (unsigned)prog_len);
    }

    pk = EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519, NULL,
                                     ls_sig_pubkey, LS_SIG_PUBKEY_LEN);
    if (pk == NULL)
        goto out;
    ctx = EVP_MD_CTX_new();
    if (ctx == NULL)
        goto out;
    /* Ed25519 is a one-shot: DigestVerify with a NULL md, then EVP_DigestVerify over the whole
     * message. There is no update/final split for it, which is one fewer way to use it wrongly. */
    if (EVP_DigestVerifyInit(ctx, NULL, NULL, NULL, pk) != 1)
        goto out;

    /* EVP_DigestVerify: 1 = verified, 0 = INVALID, negative = ERROR. Treating "!= 1" as an
     * invalid signature conflates a forgery with a broken crypto library, and on 2026-08-20 that
     * cost a diagnosis: a live refusal said "signature does not verify" while the bytes, the key
     * and the signature had each been checked correct outside TMM. Distinguish them, and say
     * which. */
    {
        int v = EVP_DigestVerify(ctx, sig, sig_len, binding, binding_len);
        if (v == 0) {
            rc = LS_SIG_BAD_SIGNATURE;
            goto out;
        }
        if (v != 1) {
            unsigned long e = ERR_peek_last_error();
            char eb[160];

            /* The OpenSSL error queue is the only thing that can distinguish "Ed25519 is not
             * available in this build" from "the arguments were wrong", and neither is a
             * verdict about the program. Logged here rather than returned, because the caller
             * gets one refusal either way. */
            ERR_error_string_n(e, eb, sizeof eb);
            fprintf(stderr, "ls_sig: EVP_DigestVerify returned %d --- %s\n", v, eb);
            rc = LS_SIG_EVP_ERROR;
            goto out;
        }
    }

    /* THE SIGNATURE COVERS THE BINDING, SO THE BODY IS ONLY AS BOUND AS ITS HASH. Skipping this
     * would let a valid signature be replayed onto any program at all --- falsifier F6c in
     * 02-RESEARCH-PARAMETERS.md. The hash lives at offset 0 of the binding; ls_sig_pubkey.h
     * asserts that against the ABI rather than trusting this comment. */
    if (SHA256((const unsigned char *)prog, prog_len, want) == NULL) {
        rc = LS_SIG_EVP_FAILED;
        goto out;
    }
    claimed = (const unsigned char *)binding + LS_SIG_BINDING_HASH_OFF;
    if (CRYPTO_memcmp(claimed, want, sizeof want) != 0) {
        rc = LS_SIG_BODY_MISMATCH;
        goto out;
    }
    rc = LS_SIG_OK;

out:
    if (ctx) EVP_MD_CTX_free(ctx);
    if (pk)  EVP_PKEY_free(pk);
    return rc;
}
