/* ls_sig.c --- the Ed25519 verification itself. See ls_sig.h for what is signed and why. */
#include "ls_sig.h"
/* ANGLE BRACKETS, and the difference is load-bearing. ls_sig_pubkey.h is a BUILD ARTIFACT ---
 * generated by gen_sig_pubkey.py from whichever key this build trusts --- not a source file
 * sitting next to this one. A quoted include searches this file's own directory first, ahead of
 * every -I, so `#include "ls_sig_pubkey.h"` silently pinned the key to whatever copy happened to
 * be committed in substrate/, and no -I order could override it.
 *
 * That is not a style point. It made the signature test verify a freshly signed program against
 * a stale committed key and report a failure of its own construction --- the most confusing way
 * for a security check to fail, and it would have done the same to any build that generated its
 * key somewhere other than this directory. */
#include <ls_sig_pubkey.h>

#include <openssl/evp.h>
#include <openssl/sha.h>

#include <stdio.h>
#include <string.h>

const char *
ls_sig_strerror(enum ls_sig_result r)
{
    switch (r) {
    case LS_SIG_OK:             return "ok";
    case LS_SIG_NO_PUBKEY:      return "no public key is baked into this build";
    case LS_SIG_BAD_ARGS:       return "malformed request (length or pointer)";
    case LS_SIG_EVP_FAILED:     return "the crypto library could not attempt verification";
    case LS_SIG_BAD_SIGNATURE:  return "signature does not verify against the binding";
    case LS_SIG_BODY_MISMATCH:  return "signature is valid but the program body does not match "
                                       "the hash it commits to";
    }
    return "unknown";
}

int
ls_sig_have_pubkey(void)
{
    /* An all-zero key is the "unset" state that a generated header with no key produces. Treat
     * it as absent rather than as a key, because a zero key is a valid Ed25519 point and would
     * otherwise silently verify nothing while looking configured. */
    unsigned i;

    if (LS_SIG_PUBKEY_LEN != 32u)
        return 0;
    for (i = 0; i < LS_SIG_PUBKEY_LEN; i++)
        if (ls_sig_pubkey[i] != 0)
            return 1;
    return 0;
}

enum ls_sig_result
ls_sig_verify(const void *binding, size_t binding_len,
              const uint8_t *sig, size_t sig_len,
              const void *prog, size_t prog_len)
{
    EVP_PKEY *pk = NULL;
    EVP_MD_CTX *ctx = NULL;
    enum ls_sig_result rc = LS_SIG_EVP_FAILED;
    unsigned char want[32];
    const unsigned char *claimed;

    /* ARGUMENTS FIRST, because a caller controls every one of them. A short binding is refused
     * rather than padded: padding would make two different requests verify against one
     * signature. */
    if (binding == NULL || sig == NULL || prog == NULL)
        return LS_SIG_BAD_ARGS;
    if (binding_len != LS_SIG_BINDING_LEN || sig_len != 64u || prog_len == 0)
        return LS_SIG_BAD_ARGS;
    if (!ls_sig_have_pubkey())
        return LS_SIG_NO_PUBKEY;

    pk = EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519, NULL,
                                     ls_sig_pubkey, LS_SIG_PUBKEY_LEN);
    if (pk == NULL)
        goto out;
    ctx = EVP_MD_CTX_new();
    if (ctx == NULL)
        goto out;
    /* Ed25519 is a one-shot: DigestVerify with a NULL md, then EVP_DigestVerify over the whole
     * message. There is no update/final split for it, which is one fewer way to use it wrongly. */
    if (EVP_DigestVerifyInit(ctx, NULL, NULL, NULL, pk) != 1)
        goto out;

    if (EVP_DigestVerify(ctx, sig, sig_len, binding, binding_len) != 1) {
        rc = LS_SIG_BAD_SIGNATURE;
        goto out;
    }

    /* THE SIGNATURE COVERS THE BINDING, SO THE BODY IS ONLY AS BOUND AS ITS HASH. Skipping this
     * would let a valid signature be replayed onto any program at all --- falsifier F6c in
     * 02-RESEARCH-PARAMETERS.md. The hash lives at offset 0 of the binding; ls_sig_pubkey.h
     * asserts that against the ABI rather than trusting this comment. */
    if (SHA256((const unsigned char *)prog, prog_len, want) == NULL) {
        rc = LS_SIG_EVP_FAILED;
        goto out;
    }
    claimed = (const unsigned char *)binding + LS_SIG_BINDING_HASH_OFF;
    if (CRYPTO_memcmp(claimed, want, sizeof want) != 0) {
        rc = LS_SIG_BODY_MISMATCH;
        goto out;
    }
    rc = LS_SIG_OK;

out:
    if (ctx) EVP_MD_CTX_free(ctx);
    if (pk)  EVP_PKEY_free(pk);
    return rc;
}
