/* GENERATED by substrate/gen_sig_pubkey.py --- do not edit.
 *
 * The Ed25519 public key this build will accept signatures from.
 *   origin      : /tmp/test_pk.pem
 *   sha256(key) : 792f6f0e338b2ee2f5437d41823016932f2cc1c65e9aedcde4754cccd1f22f52
 *
 * Regenerate whenever the signing key changes. The fingerprint above is what an
 * operator compares against the signing service's key --- if they differ, this
 * build trusts something else.
 */
#ifndef LS_SIG_PUBKEY_H
#define LS_SIG_PUBKEY_H

#include <stdint.h>

#define LS_SIG_PUBKEY_LEN 32u

/* Offsets into struct shield_binding, asserted against the ABI in check_sig.c so
 * this header cannot drift from shield_abi.h without a build failure. */
#define LS_SIG_BINDING_LEN      112u
#define LS_SIG_BINDING_HASH_OFF   0u

static const uint8_t ls_sig_pubkey[LS_SIG_PUBKEY_LEN] = {
    0x0f, 0xf0, 0x96, 0x9b, 0x0c, 0x61, 0xdb, 0x3b,
    0xf1, 0x94, 0xc5, 0x8b, 0x1e, 0x60, 0xe3, 0x99,
    0x53, 0xae, 0x09, 0x00, 0x38, 0x76, 0x22, 0x3b,
    0xe3, 0x7f, 0x08, 0x03, 0x6d, 0xfc, 0x3a, 0xb6,
};

#endif /* LS_SIG_PUBKEY_H */
