/* ls_tramp_asm.c --- the validated trampoline_x86_64.S, wrapped in a file-scope
   asm block because the TMM filelist compiles C only. Generated; do not hand-edit. */
#if defined(__x86_64__)
__asm__(
"/*\n"
" * trampoline_x86_64.S --- the patched-entry trampoline, System V AMD64.\n"
" *\n"
" * ===================================================================\n"
" *  WHY THIS EXISTS, given that the VM already works without it\n"
" * ===================================================================\n"
" *\n"
" * The integration built on 2026-08-12 uses a DESIGNED-IN call site: 39 lines of\n"
" * C added to http_psm.c, where the compiler owns the calling convention and the\n"
" * shim is arch-generic C. That works, and it needs none of this file.\n"
" *\n"
" * This is for the other claim --- attaching to a function NOBODY EDITED. There\n"
" * the compiler reserved a few bytes at the entry and arming rewrites them into a\n"
" * CALL to here. There is no C frame to borrow, so everything the ABI says a\n"
" * caller may rely on has to be preserved by hand. That is the whole content of\n"
" * this file, and it is why development-scope.md calls item 1 badly understated\n"
" * at \"a page of asm per arch\": the assembly is short, the ABI edge cases are not.\n"
" *\n"
" * ===================================================================\n"
" *  MEASURED FACTS ABOUT THE TARGET --- not assumptions\n"
" * ===================================================================\n"
" *\n"
" * From the BNK build of tmm/tmm at e2104734a9, x86-64\n"
" * (tmm64.no_pgo, build-id verified against its own debug file):\n"
" *\n"
" *   1. IBT IS ON.  403 of 500 sampled functions begin with `endbr64`\n"
" *      (f3 0f 1e fa).  Any indirect branch to a location without an endbranch\n"
" *      faults on CET hardware, so THIS TRAMPOLINE MUST START WITH ONE, and the\n"
" *      patch must not destroy the target's own.\n"
" *\n"
" *   2. THE PAD SITS AFTER endbr64.  With -fpatchable-function-entry=5,0 the\n"
" *      nops are emitted after the entry label, and with IBT they land after the\n"
" *      endbranch:  f3 0f 1e fa  90 90 90 90 90\n"
" *      That is why FIVE is the right pad: `call rel32` is exactly 5 bytes\n"
" *      (e8 xx xx xx xx), so arming replaces the nops in place and DISPLACES NO\n"
" *      REAL INSTRUCTION.  Nothing has to be relocated or re-executed --- which\n"
" *      removes the single largest source of complexity in this kind of hook.\n"
" *\n"
" *      IT MUST BE `call`, NOT `jmp`, and an earlier draft of this file said\n"
" *      jmp.  A jmp pushes nothing, so the `ret` on the fall-through path below\n"
" *      would return to the hooked function's CALLER --- i.e. it would silently\n"
" *      behave as a safe return, always, and the body would never run.  `call`\n"
" *      pushes the address of the instruction after the patch, which IS the\n"
" *      body, so `ret` continues into it.  Verified on hardware, not reasoned:\n"
" *      see check-tramp, which patches a stand-in function and asserts that the\n"
" *      body runs on fall-through and does not on safe return.\n"
" *\n"
" *   3. ARGUMENTS MOVE IMMEDIATELY.  A real target begins\n"
" *          mov %rcx,%r12 ; push %rbp ; mov %rdx,%rbp ; push %rbx ; sub $0x28,%rsp\n"
" *      so the argument registers are consumed within the first few instructions.\n"
" *      The trampoline therefore runs BEFORE the prologue and must capture them\n"
" *      first; there is no later point at which rdi/rsi/rdx/rcx still hold the\n"
" *      arguments.\n"
" *\n"
" *   4. .eh_frame IS PRESENT.  A core dump taken while a shield is running must\n"
" *      still unwind, so this file carries CFI directives.  Without them the\n"
" *      backtrace stops here, and \"the crash we were shielding is now\n"
" *      undebuggable\" is not an acceptable trade.\n"
" *\n"
" * ===================================================================\n"
" *  WHAT THIS FILE DOES NOT DO\n"
" * ===================================================================\n"
" *\n"
" *   - It does not save FP/SIMD state.  See the note at ls_tramp_save_fp below:\n"
" *     that is a real decision, not an omission, and it is wrong for any hook\n"
" *     whose shield might touch floating point.\n"
" *   - It does not handle varargs (%rax as the vector-register count).\n"
" *   - It does not implement the safe-return path's value selection --- the host\n"
" *     decides what a safe return means per hook (development-scope.md item 7);\n"
" *     this returns the value the hook slot carries.\n"
" *   - It is NOT re-entrant.  ls_vm.c hands every invocation the same per-instance\n"
" *     program stack, which is safe only because TMM is run-to-completion and two\n"
" *     invocations never overlap on a core.  A shield that re-entered its own\n"
" *     hooked path would corrupt that stack.  Guarding it is on item 1's list.\n"
" *   - It is not wired to anything.  Arming (item 2) writes the jump; nothing here\n"
" *     writes code.\n"
" *\n"
" * Status: candidate artifact.  It assembles.  Nothing calls it.\n"
" */\n"
"\n"
"    .text\n"
"    .globl  ls_trampoline_entry\n"
"    .type   ls_trampoline_entry, @function\n"
"\n"
"/*\n"
" * Reached by the 5-byte `call rel32` written over the patch nops.  On entry the\n"
" * stack and registers are exactly as the hooked function's caller left them,\n"
" * except that the call has pushed the address of the instruction AFTER the\n"
" * patch --- i.e. the hooked function's real body.\n"
" *\n"
" * REACH: `call rel32` spans +/-2GB from the patch site.  TMM's .text is ~30MB,\n"
" * so a trampoline living in .text is always in range.  A trampoline in\n"
" * mmap'd memory is NOT guaranteed to be, and five bytes cannot hold an indirect\n"
" * call --- so either the trampoline is linked into the image, or arming must\n"
" * allocate its trampolines within +/-2GB of .text and fail closed when it\n"
" * cannot.  That constraint belongs to item 2 and is easy to miss until a large\n"
" * ASLR offset makes it intermittent.\n"
" */\n"
"ls_trampoline_entry:\n"
"    .cfi_startproc\n"
"    endbr64                         /* fact 1: IBT. Without this, the indirect\n"
"                                     * branch faults on CET hardware. */\n"
"\n"
"    /*\n"
"     * Fact 3: capture the argument registers before anything else can clobber\n"
"     * them.  System V AMD64 integer arguments, in order:\n"
"     *     rdi rsi rdx rcx r8 r9\n"
"     * rax additionally carries the vector-register count for varargs calls,\n"
"     * which this file does not support --- see the header.\n"
"     */\n"
"    pushq   %rdi\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %rsi\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %rdx\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %rcx\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %r8\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %r9\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %rax\n"
"    .cfi_adjust_cfa_offset 8\n"
"\n"
"    /*\n"
"     * Caller-saved registers the shield path may clobber.  r10 and r11 are\n"
"     * scratch under the ABI, so the hooked function cannot rely on them --- but\n"
"     * WE are running before the hooked function, on behalf of its caller, and\n"
"     * the caller cannot rely on them either.  Saved anyway: the cost is two\n"
"     * pushes, and the failure mode if this reasoning is ever wrong is a\n"
"     * miscompile-class bug that would take days to find.\n"
"     */\n"
"    pushq   %r10\n"
"    .cfi_adjust_cfa_offset 8\n"
"    pushq   %r11\n"
"    .cfi_adjust_cfa_offset 8\n"
"\n"
"    /*\n"
"     * Align to 16 before the call.  Nine pushes above (72 bytes) plus the 8-byte\n"
"     * return address leaves rsp ≡ 0 (mod 16) already, but the alignment is\n"
"     * asserted rather than assumed, because getting it wrong shows up only when\n"
"     * the callee happens to use an aligned SSE move.\n"
"     */\n"
"    subq    $8, %rsp\n"
"    .cfi_adjust_cfa_offset 8\n"
"\n"
"    /*\n"
"     * ls_tramp_dispatch(slot, arg0..arg5) --- plain C, in ls_tramp.c.\n"
"     *\n"
"     * The ctx build lives in C on purpose.  It is per-hook, generated from the\n"
"     * build's DWARF (item 6), and changes whenever a hook's signature does;\n"
"     * putting it in assembly would mean regenerating assembly per hook, which is\n"
"     * the thing this design is trying to avoid.  The assembly is generic; only\n"
"     * the C is per-hook.\n"
"     *\n"
"     * THE SLOT INDEX IS A PATCHED IMMEDIATE, not a register.\n"
"     *\n"
"     * An earlier draft of this file said the slot \"arrives in r11\".  That is\n"
"     * wrong: at hook entry r11 holds whatever the hooked function's CALLER left\n"
"     * there.  Nothing has put a slot index in it, and reading it would feed the\n"
"     * dispatcher garbage.\n"
"     *\n"
"     * This is one trampoline per armed hook, so the slot is known when the\n"
"     * trampoline is created.  `movl $imm32` puts it in the instruction stream;\n"
"     * arming (item 2) writes the four bytes at ls_tramp_slot_imm.  A single\n"
"     * SHARED trampoline is the alternative and would have to recover the slot\n"
"     * from the return address --- possible, slower, and a trade that belongs to\n"
"     * item 2 rather than here.\n"
"     */\n"
"    .globl  ls_tramp_slot_insn\n"
"ls_tramp_slot_insn:                 /* arming rewrites the 4 bytes at +1        */\n"
"    movl    $0x7fffffff, %edi       /* slot --- placeholder, patched at arm     */\n"
"    /*\n"
"     * The label sits on the INSTRUCTION, not on the immediate.  An earlier draft\n"
"     * used `ls_tramp_slot_imm = . + 1` to point straight at the four bytes;\n"
"     * the code was correct, but a symbol in the middle of an instruction makes\n"
"     * objdump restart disassembly there and render everything after it as\n"
"     * garbage --- in the one file whose whole audience is someone reading a\n"
"     * disassembler.  Arming adds the +1 itself; that is one line in item 2\n"
"     * against permanently unreadable output here.\n"
"     */\n"
"    /*\n"
"     * Stack layout at this point, from rsp upward.  Nine pushes (72 bytes) then\n"
"     * `sub $8`, so the saved registers begin at 8(%rsp):\n"
"     *\n"
"     *    0  alignment gap      40  r8\n"
"     *    8  r11                48  rcx\n"
"     *   16  r10                56  rdx\n"
"     *   24  rax                64  rsi\n"
"     *   32  r9                 72  rdi   <- the hooked function's arg0\n"
"     *   80  return address (into the hooked function's body)\n"
"     *\n"
"     * An earlier draft had every one of these eight bytes low --- it read rsi as\n"
"     * rdi, rdx as rsi, and so on.  That does not crash; it silently hands the\n"
"     * shield the wrong arguments, which is the worst way for this to be wrong.\n"
"     */\n"
"    movq    72(%rsp), %rsi          /* saved rdi = hooked function's arg0      */\n"
"    movq    64(%rsp), %rdx          /* saved rsi = arg1                        */\n"
"    movq    56(%rsp), %rcx          /* saved rdx = arg2                        */\n"
"    movq    48(%rsp), %r8           /* saved rcx = arg3                        */\n"
"    movq    40(%rsp), %r9           /* saved r8  = arg4                        */\n"
"\n"
"    /*\n"
"     * Returns a {int verdict; uint64_t safe_value} pair, which System V returns\n"
"     * in rax:rdx --- exactly the registers the code below reads.  An earlier\n"
"     * draft passed a seventh `safe_out` POINTER argument, which the ABI would\n"
"     * have placed on the stack while this call site passed only six registers:\n"
"     * the callee would have dereferenced whatever happened to be there.\n"
"     */\n"
"    call    ls_tramp_dispatch       /* -> eax: 0 fall through, 1 safe return   */\n"
"                                    /*    rdx: the declared safe value          */\n"
"\n"
"    addq    $8, %rsp\n"
"    .cfi_adjust_cfa_offset -8\n"
"\n"
"    testl   %eax, %eax\n"
"    jnz     .Lsafe_return\n"
"\n"
"    /*\n"
"     * Fall through: restore everything and continue into the hooked function's\n"
"     * real body.  Fact 2 is what makes this trivial --- the patch overwrote only\n"
"     * nops, so the body is intact and the return address already points at it.\n"
"     * `ret` therefore lands exactly where execution would have gone had nothing\n"
"     * been armed.\n"
"     */\n"
"    popq    %r11\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %r10\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %rax\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %r9\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %r8\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %rcx\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %rdx\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %rsi\n"
"    .cfi_adjust_cfa_offset -8\n"
"    popq    %rdi\n"
"    .cfi_adjust_cfa_offset -8\n"
"    ret\n"
"\n"
".Lsafe_return:\n"
"    /*\n"
"     * Safe return: the hooked function's body must NOT run.  Discard the saved\n"
"     * registers, drop the return address that points into the body, and return\n"
"     * to the hooked function's own caller with the declared safe value.\n"
"     *\n"
"     * ls_tramp_dispatch leaves that value in rdx --- chosen because rax already\n"
"     * carries the verdict.  What counts as safe is per-hook and belongs to the\n"
"     * safe-return policy table (item 7); this file only delivers it.\n"
"     *\n"
"     * THE LIMIT WORTH STATING: this is correct only for a return type that fits\n"
"     * in rax.  A struct returned by hidden pointer, or anything using rdx:rax or\n"
"     * the x87/SSE return registers, needs its own path.  Item 7 restricts v1 to\n"
"     * trivial returns for exactly this reason, and this file enforces nothing ---\n"
"     * admitting a shield on a hook with a non-trivial return type is an\n"
"     * admission-time error, not a runtime one.\n"
"     */\n"
"    addq    $72, %rsp               /* discard the nine saved registers        */\n"
"    .cfi_adjust_cfa_offset -72\n"
"    movq    %rdx, %rax              /* the declared safe value                 */\n"
"    addq    $8, %rsp                /* drop the return-into-body address       */\n"
"    .cfi_adjust_cfa_offset -8\n"
"    ret                             /* -> the hooked function's caller         */\n"
"\n"
"    .cfi_endproc\n"
"    .size   ls_trampoline_entry, .-ls_trampoline_entry\n"
"\n"
"/*\n"
" * FP/SIMD, deliberately absent.\n"
" *\n"
" * Saving xmm0-15 costs ~256 bytes of stack and 16 stores/loads per invocation,\n"
" * on a path whose whole budget is ~26 cycles (the measured JIT floor).  It would\n"
" * dominate.  It is omitted here because uBPF's generated code does not touch\n"
" * SSE --- but that is a property of TODAY'S uBPF, not a guarantee, and it does\n"
" * not hold if a helper is ever added that does.\n"
" *\n"
" * So this is a bet, and it should be an explicit one: either the admission\n"
" * pipeline proves the program touches no FP state, or the trampoline pays for\n"
" * it.  Choosing silently is how a rare, data-dependent corruption gets shipped.\n"
" */\n"
"    .section .note.GNU-stack,\"\",@progbits\n"
);
#endif
