#!/usr/bin/env python3
"""Generate ls_shield_blob.h --- the built-in shield, baked into TMM as bytes.

WHY THIS EXISTS. ls_vm_load.c includes "ls_shield_blob.h" and arms it at startup
(ls_vm_bootstrap). That header is GENERATED, was produced by hand on the build
box, and was never committed --- so `make check` in this repo failed with
"ls_shield_blob.h: No such file or directory" and nobody could compile the
loader. This script is the missing generator.

WHAT THE BLOB IS FOR. TMM arms one shield at startup with no socket, no operator
and no network involved, so the mechanism is exercised on every boot rather than
only when someone drives it. It is the reason a broken load path showed up as a
boot-time symptom instead of silence.

    The blob is NOT how a real shield would ship. Baking a program into the
    binary makes it a rebuild, which is the exact property this project exists
    to remove. It is a development convenience and a self-test, and the runtime
    load path (SHIELD_OP_LOAD over the socket) is the real mechanism.

IDENTITY. Both names are emitted alongside the bytes because uBPF and PREVAIL
disagree about what identifies a program: PREVAIL proves a SECTION, uBPF runs a
SYMBOL. ls_vm_reload refuses to run a program whose section does not match the
hook it was submitted under (finding O14), so the two must be emitted together
and stay together.

usage:  mk_shield_blob.py [-o ls_shield_blob.h] [--source shields/ls_2026_http_psm.bpf.c]
"""
import argparse, os, shutil, subprocess, sys, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRC = os.path.join(HERE, "shields", "ls_2026_http_psm.bpf.c")
DEFAULT_OUT = os.path.join(HERE, "ls_shield_blob.h")

# The hook the built-in shield guards, and the section its source declares.
# ls_vm_load.c builds "fentry/<hook>" and compares; keep these consistent with
# shields/ls_2026_http_psm.bpf.c or the loader will refuse its own blob.
FUNCTION = "shield"
HOOK = "http_psm_profile_name_lookup"


def compile_bpf(src, obj):
    clang = shutil.which("clang") or shutil.which("clang-18")
    if not clang:
        return None, "no clang on PATH"
    cmd = [clang, "-O2", "-g", "-target", "bpf", "-c", src, "-o", obj]
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        return None, (p.stderr.strip().splitlines() or ["clang failed"])[-1]
    return obj, None


def emit(blob, src, out, section, function):
    body = ",\n".join(
        "    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 12])
        for i in range(0, len(blob), 12)
    )
    # Dedent the template BEFORE the body goes in. textwrap.dedent() computes the
    # common prefix over every line it is handed, so interpolating the already
    # indented byte rows first makes it strip 4 spaces instead of 8 and leaves the
    # whole generated header indented.
    header = textwrap.dedent(f"""\
        /* GENERATED by substrate/mk_shield_blob.py --- do not hand-edit.
         *
         * The shield TMM arms at startup, as bytes. Source: {os.path.basename(src)}
         * ({len(blob)} bytes of ELF, compiled with clang -O2 -g -target bpf).
         *
         * Regenerate with:  make -C substrate shield-blob
         *
         * BOTH identities are here on purpose. PREVAIL proves a SECTION and uBPF
         * runs a SYMBOL; ls_vm_reload refuses a program whose section does not
         * match the hook it was submitted under (finding O14). Changing one of
         * these without the other makes TMM refuse its own built-in shield at
         * boot --- which is the intended behaviour, not a bug.
         *
         * This blob is a development convenience and a boot self-test. Shipping a
         * shield this way would make it a rebuild, which is the property this
         * project exists to remove. The socket load path is the real mechanism.
         */
        #ifndef LS_SHIELD_BLOB_H
        #define LS_SHIELD_BLOB_H

        #define LS_SHIELD_SECTION   "{section}"
        #define LS_SHIELD_FUNCTION  "{function}"

        static const unsigned char ls_shield_blob[] = {{
        __BODY__
        }};

        #endif /* LS_SHIELD_BLOB_H */
        """).replace("__BODY__", body)
    with open(out, "w") as f:
        f.write(header)
    return len(blob)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=DEFAULT_SRC)
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    ap.add_argument("--hook", default=HOOK)
    ap.add_argument("--function", default=FUNCTION)
    a = ap.parse_args()

    if not os.path.exists(a.source):
        print(f"*** no such source: {a.source}", file=sys.stderr)
        return 2

    obj = os.path.join("/tmp", ".ls_shield_blob.o")
    built, err = compile_bpf(a.source, obj)
    if not built:
        print(f"skip  ls_shield_blob.h  ({err}; leaving any existing header alone)")
        return 0 if os.path.exists(a.out) else 3

    with open(built, "rb") as f:
        blob = f.read()
    os.unlink(built)

    n = emit(blob, a.source, a.out, f"fentry/{a.hook}", a.function)
    print(f"ok    ls_shield_blob.h  ({n} bytes, section fentry/{a.hook}, symbol {a.function})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
