#!/usr/bin/env python3
"""tmmtrace --- the Live Surface trace DSL front-end (Phase 1: codegen + verify).

bpftrace-for-the-data-plane. You write a one-line trace expression; tmmtrace emits
a CO-RE eBPF program in the exact shape the substrate's surfaces use, then (with
--verify) compiles it with clang -target bpf and runs it through PREVAIL --- the
same admission gate a hand-written surface goes through. The novel part is this
front-end: everything downstream (verify -> sign -> arm -> drain) already exists.

GRAMMAR (Phase 1 subset)
    <probe> '{' <action> '}'
    <probe>  := ('fentry'|'fexit') '/' <hook>
    <action> := 'count'                                  # return 1; host counts `fired`
              | 'arg' <N>                                # return the raw scalar arg[N]
              | <struct> '(' 'arg' <N> ')' '.' <field> [ ':' <ty> ]
                                                         # CO-RE-read <field> of <struct>*
                                                         # from arg[N]; <ty> default u64
    <ty> := u8 | u16 | u32 | u64

WHY THE <struct> IS EXPLICIT (for now). CO-RE resolves a field by NAME against the
build's BTF, but the program still has to name the type it is reading through. A
hand-written surface writes `struct http_parse_ctx { ... }`; Phase 1 takes that
name from the expression. Phase 2 will look it up from the per-build hook map
(arg_btf) so you can write the bpftrace-style `args.<field>` and skip the type ---
that map is the "ctx descriptor" the design doc flags as the real 90%.

EXAMPLES
    tmmtrace.py gen    'fentry/http_parse_client_headers { http_parse_ctx(arg0).version_num:u8 }'
    tmmtrace.py verify 'fentry/dtls_tx { count }'
    tmmtrace.py verify 'fentry/http_parse_client_headers { http_parse_ctx(arg0).version_num:u8 }'
"""
import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLANG = os.environ.get("CLANG", "clang-14")
PREVAIL = os.environ.get("PREVAIL", os.path.join(REPO, "ebpf-verifier", "bin", "prevail"))

CTYPE = {"u8": "__u8", "u16": "__u16", "u32": "__u32", "u64": "__u64"}

# <probe> { <action> }
_PROBE = re.compile(r"^\s*(fentry|fexit)/([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*(.*?)\s*\}\s*$")
# <struct>(argN).<field>[:<ty>]
_FIELD = re.compile(
    r"^([A-Za-z_][A-Za-z0-9_]*)\(arg([0-4])\)\.([A-Za-z_][A-Za-z0-9_]*)(?::(u8|u16|u32|u64))?$"
)
_ARG = re.compile(r"^arg([0-4])$")


class DslError(Exception):
    pass


def parse(expr):
    m = _PROBE.match(expr)
    if not m:
        raise DslError("expected  <fentry|fexit>/<hook> { <action> }")
    section, hook, action = m.group(1), m.group(2), m.group(3).strip()
    return section, hook, action


def _ident(section, hook, action):
    """A stable, valid C identifier for the generated program/function."""
    tag = re.sub(r"[^A-Za-z0-9_]", "_", action)[:24].strip("_") or "probe"
    return "tt_%s_%s" % (hook, tag)


def codegen(expr):
    section, hook, action = parse(expr)
    fn = _ident(section, hook, action)
    ctx = "ls_ctx_exit" if section == "fexit" else "ls_ctx_generic"
    # the flat register context the trampoline hands every program
    ctxdef = ("struct ls_ctx_exit { __u64 arg[5]; __u64 ret; };"
              if section == "fexit"
              else "struct ls_ctx_generic { __u64 arg[5]; };")

    head = [
        "/* generated by tmmtrace from:  %s */" % expr,
        "typedef unsigned char __u8; typedef unsigned short __u16;",
        "typedef unsigned int __u32; typedef unsigned long long __u64;",
        "static long (*bpf_probe_read)(void *, __u32, const void *) = (void *)4;",
    ]

    if action == "count":
        body = "    return 1ull;                      /* host counts `fired` */"
        structs = ""
    elif _ARG.match(action):
        n = _ARG.match(action).group(1)
        body = "    return c->arg[%s];                 /* raw scalar arg */" % n
        structs = ""
    else:
        fm = _FIELD.match(action)
        if not fm:
            raise DslError(
                "action must be  count | arg<N> | <struct>(arg<N>).<field>[:<ty>]")
        struct, n, field, ty = fm.group(1), fm.group(2), fm.group(3), fm.group(4) or "u64"
        ct = CTYPE[ty]
        # minimal CO-RE view: just the field read; the offset is relocated by name
        structs = ("struct %s { %s %s; } __attribute__((preserve_access_index));"
                   % (struct, ct, field))
        body = (
            "    struct %s *p = (struct %s *)c->arg[%s];\n"
            "    %s v = 0;\n"
            "    if (bpf_probe_read(&v, sizeof v, &p->%s) != 0)\n"
            "        return 0ull;\n"
            "    return (__u64)v;" % (struct, struct, n, ct, field)
        )

    lines = head + [
        structs,
        ctxdef,
        "",
        '__attribute__((section("%s/%s"), used))' % (section, hook),
        "__u64 %s(struct %s *c)" % (fn, ctx),
        "{",
        body,
        "}",
        "",
    ]
    return "\n".join(l for l in lines if l is not None), fn, section, hook


def verify(expr):
    src, fn, section, hook = codegen(expr)
    if not os.path.exists(PREVAIL):
        sys.exit("*** PREVAIL not found at %s (set $PREVAIL); run this in the dev sandbox"
                 % PREVAIL)
    with tempfile.TemporaryDirectory() as d:
        c = os.path.join(d, "%s.bpf.c" % fn)
        o = os.path.join(d, "%s.bpf.o" % fn)
        open(c, "w").write(src)
        cc = subprocess.run(
            [CLANG, "-O2", "-g", "-target", "bpf", "-c", c, "-o", o],
            capture_output=True, text=True)
        if cc.returncode != 0:
            print(src)
            sys.exit("*** clang failed:\n" + cc.stderr)
        sec = "%s/%s" % (section, hook)
        pv = subprocess.run(
            [PREVAIL, o, sec, "--termination", "--allow-division-by-zero"],
            capture_output=True, text=True)
        ok = pv.returncode == 0
        # PREVAIL prints a cycle-ish figure; surface whatever it emits
        note = (pv.stdout or pv.stderr or "").strip().splitlines()
        print("program : %s   section %s" % (fn, sec))
        print("clang   : ok")
        print("PREVAIL : %s" % ("VERIFIED" if ok else "REFUSED"))
        for l in note[:3]:
            print("          %s" % l)
        return 0 if ok else 1


def main(argv):
    if len(argv) < 3 or argv[1] not in ("gen", "verify"):
        sys.exit(__doc__)
    expr = argv[2]
    try:
        if argv[1] == "gen":
            src, _fn, _s, _h = codegen(expr)
            sys.stdout.write(src)
            return 0
        return verify(expr)
    except DslError as e:
        sys.exit("*** DSL error: %s\n    in: %s" % (e, expr))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
