#!/usr/bin/env python3
"""tmmtrace --- the Live Surface trace DSL front-end (Phase 1: codegen + verify).

bpftrace-for-the-data-plane. You write a one-line trace expression; tmmtrace emits
a CO-RE eBPF program in the exact shape the substrate's surfaces use, then (with
--verify) compiles it with clang -target bpf and runs it through PREVAIL --- the
same admission gate a hand-written surface goes through. The novel part is this
front-end: everything downstream (verify -> sign -> arm -> drain) already exists.

GRAMMAR (Phase 1 subset)
    <probe> '{' <action> '}'
    <probe>  := ('fentry'|'fexit') '/' <hook>
    <action> := 'count'                                  # return 1; host counts `fired`
              | 'arg' <N>                                # return the raw scalar arg[N]
              | <struct> '(' 'arg' <N> ')' '.' <field> [ ':' <ty> ]
                                                         # CO-RE-read <field> of <struct>*
                                                         # from arg[N]; <ty> default u64
    <ty> := u8 | u16 | u32 | u64

WHY THE <struct> IS EXPLICIT (for now). CO-RE resolves a field by NAME against the
build's BTF, but the program still has to name the type it is reading through. A
hand-written surface writes `struct http_parse_ctx { ... }`; Phase 1 takes that
name from the expression. Phase 2 will look it up from the per-build hook map
(arg_btf) so you can write the bpftrace-style `args.<field>` and skip the type ---
that map is the "ctx descriptor" the design doc flags as the real 90%.

EXAMPLES
    tmmtrace.py gen    'fentry/http_parse_client_headers { http_parse_ctx(arg0).version_num:u8 }'
    tmmtrace.py verify 'fentry/dtls_tx { count }'
    tmmtrace.py verify 'fentry/http_parse_client_headers { http_parse_ctx(arg0).version_num:u8 }'
"""
import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLANG = os.environ.get("CLANG", "clang-14")
PREVAIL = os.environ.get("PREVAIL", os.path.join(REPO, "ebpf-verifier", "bin", "prevail"))

CTYPE = {"u8": "__u8", "u16": "__u16", "u32": "__u32", "u64": "__u64"}

# <probe> { <action> }
_PROBE = re.compile(r"^\s*(fentry|fexit)/([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*(.*?)\s*\}\s*$")
# <struct>(argN).<field>[:<ty>]
_FIELD = re.compile(
    r"^([A-Za-z_][A-Za-z0-9_]*)\(arg([0-4])\)\.([A-Za-z_][A-Za-z0-9_]*)(?::(u8|u16|u32|u64))?$"
)
_ARG = re.compile(r"^arg([0-4])$")
# Phase 2 implicit forms
_ARGSDOT = re.compile(r"^args\.([A-Za-z_]\w*)$")          # args.<name>
_ARGNDOT = re.compile(r"^arg([0-4])\.([A-Za-z_]\w*)$")    # arg<N>.<field>

# Per-build type sources (generated by the build; see bnk-bake-tools). Override
# with $LS_SIGS / $LS_TYPES.
SIGS = os.environ.get("LS_SIGS", os.path.expanduser("~/lstools/signatures.tsv"))
TYPES = os.environ.get("LS_TYPES", os.path.expanduser("~/lstools/types.json"))
_STRUCT_PTR = re.compile(r"struct\s+(\w+)\s*\*")


class DslError(Exception):
    pass


_types_cache = None
_sigs_cache = None


def _types():
    global _types_cache
    if _types_cache is None:
        try:
            import json as _j
            _types_cache = _j.load(open(TYPES))
        except Exception:
            _types_cache = {}
    return _types_cache


def hook_params(hook):
    """[(param_name, kind, struct_or_ctype)] for a hook, from signatures.tsv.
    kind is 'blob' (struct pointer), 'scalar', or 'string'."""
    global _sigs_cache
    if _sigs_cache is None:
        _sigs_cache = {}
        try:
            for ln in open(SIGS):
                if ln.startswith("#"):
                    continue
                f = ln.rstrip("\n").split("\t")
                if len(f) >= 3:
                    _sigs_cache[f[0]] = f[2]
        except Exception:
            pass
    spec = _sigs_cache.get(hook)
    if not spec:
        return None
    out = []
    for p in spec.split("|"):
        parts = p.split(":", 2)
        if len(parts) != 3:
            continue
        name, kind, detail = parts
        struct = None
        m = _STRUCT_PTR.search(detail)
        if m:
            struct = m.group(1)
        out.append((name, kind, struct, detail))
    return out


def resolve_action(hook, action):
    """Normalize an action to one of:
        ('count',) | ('scalar', N) | ('field', struct, N, field, ty)
    handling count | argN | args.<name> | arg<N>.<field> | <struct>(argN).<field>[:ty]."""
    if action == "count":
        return ("count",)
    m = _ARG.match(action)
    if m:
        return ("scalar", int(m.group(1)))
    # explicit: <struct>(argN).<field>[:ty]
    fe = _FIELD.match(action)
    if fe:
        struct, n, field, ty = fe.group(1), int(fe.group(2)), fe.group(3), fe.group(4) or "u64"
        return ("field", struct, n, field, ty)
    params = hook_params(hook)
    # args.<name>
    ad = _ARGSDOT.match(action)
    an = _ARGNDOT.match(action)
    if ad or an:
        if params is None:
            raise DslError("no signature for hook '%s' (need %s); use the explicit "
                           "<struct>(argN).<field>:ty form" % (hook, SIGS))
        name = (ad or an).group(2) if an else ad.group(1)
        n_only = int(an.group(1)) if an else None
        # 1) a scalar parameter named <name>  -> raw arg
        for i, (pn, kind, struct, detail) in enumerate(params):
            if (n_only is None or i == n_only) and pn == name and kind in ("scalar", "string"):
                return ("scalar", i)
        # 2) a field of a struct-pointer parameter
        for i, (pn, kind, struct, detail) in enumerate(params):
            if n_only is not None and i != n_only:
                continue
            if kind == "blob" and struct and name in _types().get(struct, {}):
                return ("field", struct, i, name, _types()[struct][name])
        raise DslError("could not resolve '%s' at %s from the type data; "
                       "known: params=%s" % (name, hook,
                       ", ".join("%s(%s)" % (p[0], p[2] or p[1]) for p in params)))
    raise DslError("action must be  count | arg<N> | args.<field> | arg<N>.<field> "
                   "| <struct>(arg<N>).<field>[:ty]")


def parse(expr):
    m = _PROBE.match(expr)
    if not m:
        raise DslError("expected  <fentry|fexit>/<hook> { <action> }")
    section, hook, action = m.group(1), m.group(2), m.group(3).strip()
    return section, hook, action


def _ident(section, hook, action):
    """A stable, valid C identifier for the generated program/function."""
    tag = re.sub(r"[^A-Za-z0-9_]", "_", action)[:24].strip("_") or "probe"
    return "tt_%s_%s" % (hook, tag)


def codegen(expr):
    section, hook, action = parse(expr)
    fn = _ident(section, hook, action)
    ctx = "ls_ctx_exit" if section == "fexit" else "ls_ctx_generic"
    # the flat register context the trampoline hands every program
    ctxdef = ("struct ls_ctx_exit { __u64 arg[5]; __u64 ret; };"
              if section == "fexit"
              else "struct ls_ctx_generic { __u64 arg[5]; };")

    head = [
        "/* generated by tmmtrace from:  %s */" % expr,
        "typedef unsigned char __u8; typedef unsigned short __u16;",
        "typedef unsigned int __u32; typedef unsigned long long __u64;",
        "static long (*bpf_probe_read)(void *, __u32, const void *) = (void *)4;",
    ]

    act = resolve_action(hook, action)
    if act[0] == "count":
        body = "    return 1ull;                      /* host counts `fired` */"
        structs = ""
    elif act[0] == "scalar":
        n = act[1]
        body = "    return c->arg[%d];                 /* raw scalar arg */" % n
        structs = ""
    else:                                   # ('field', struct, n, field, ty)
        _, struct, n, field, ty = act
        ct = CTYPE[ty]
        # minimal CO-RE view: just the field read; the offset is relocated by name
        structs = ("struct %s { %s %s; } __attribute__((preserve_access_index));"
                   % (struct, ct, field))
        body = (
            "    struct %s *p = (struct %s *)c->arg[%d];\n"
            "    %s v = 0;\n"
            "    if (bpf_probe_read(&v, sizeof v, &p->%s) != 0)\n"
            "        return 0ull;\n"
            "    return (__u64)v;" % (struct, struct, n, ct, field)
        )

    lines = head + [
        structs,
        ctxdef,
        "",
        '__attribute__((section("%s/%s"), used))' % (section, hook),
        "__u64 %s(struct %s *c)" % (fn, ctx),
        "{",
        body,
        "}",
        "",
    ]
    return "\n".join(l for l in lines if l is not None), fn, section, hook


def verify(expr):
    src, fn, section, hook = codegen(expr)
    if not os.path.exists(PREVAIL):
        sys.exit("*** PREVAIL not found at %s (set $PREVAIL); run this in the dev sandbox"
                 % PREVAIL)
    with tempfile.TemporaryDirectory() as d:
        c = os.path.join(d, "%s.bpf.c" % fn)
        o = os.path.join(d, "%s.bpf.o" % fn)
        open(c, "w").write(src)
        cc = subprocess.run(
            [CLANG, "-O2", "-g", "-target", "bpf", "-c", c, "-o", o],
            capture_output=True, text=True)
        if cc.returncode != 0:
            print(src)
            sys.exit("*** clang failed:\n" + cc.stderr)
        sec = "%s/%s" % (section, hook)
        pv = subprocess.run(
            [PREVAIL, o, sec, "--termination", "--allow-division-by-zero"],
            capture_output=True, text=True)
        ok = pv.returncode == 0
        # PREVAIL prints a cycle-ish figure; surface whatever it emits
        note = (pv.stdout or pv.stderr or "").strip().splitlines()
        print("program : %s   section %s" % (fn, sec))
        print("clang   : ok")
        print("PREVAIL : %s" % ("VERIFIED" if ok else "REFUSED"))
        for l in note[:3]:
            print("          %s" % l)
        return 0 if ok else 1


def main(argv):
    if len(argv) < 3 or argv[1] not in ("gen", "verify"):
        sys.exit(__doc__)
    expr = argv[2]
    try:
        if argv[1] == "gen":
            src, _fn, _s, _h = codegen(expr)
            sys.stdout.write(src)
            return 0
        return verify(expr)
    except DslError as e:
        sys.exit("*** DSL error: %s\n    in: %s" % (e, expr))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
